steps:
  # ============================================
  # BACKEND: Build and Deploy
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-rag:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-rag:latest'
      - '.'
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-rag:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-rag:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-rag'
      - '--image=gcr.io/$PROJECT_ID/demo-rag:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--max-instances=10'
      - '--add-cloudsql-instances=atomic-sled-477620-c2:us-central1:rag-postgres-db'
      - '--set-env-vars=CLOUD_SQL_CONNECTION_NAME=atomic-sled-477620-c2:us-central1:rag-postgres-db,POSTGRES_USER=app_user,POSTGRES_DB=notes_db,TOKENIZERS_PARALLELISM=false'
      - '--update-secrets=POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,AUTH_USERNAME_1=AUTH_USERNAME_1:latest,AUTH_PASSWORD_1=AUTH_PASSWORD_1:latest,AUTH_USERNAME_2=AUTH_USERNAME_2:latest,AUTH_PASSWORD_2=AUTH_PASSWORD_2:latest'

  # ============================================
  # FRONTEND: Build and Deploy
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-rag-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-rag-frontend:latest'
      - '--build-arg'
      - 'VITE_BACKEND_URL=https://demo-rag-1009993200553.us-central1.run.app'
      - '.'
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-rag-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-rag-frontend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-rag-frontend'
      - '--image=gcr.io/$PROJECT_ID/demo-rag-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--port=8080'

images:
  - 'gcr.io/$PROJECT_ID/demo-rag:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/demo-rag:latest'
  - 'gcr.io/$PROJECT_ID/demo-rag-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/demo-rag-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1800s'
